### ISSUE TITLE
ch07 sections 'Parse' and 'Refused to load font' errors

### ISSUE THREAD

**Issue by mpwashburn** [EthanRBrown/web-development-with-node-and-express#100]
Hello,
I have gone through and quadruple checked my code to yours here in github for chapter 7. I cannot seem to figure out why sections is not working. Here are the errors I'm getting:

This is at the command line:
> Error: Parse error on line 10:
...    {{/if}}    {{{#_sections.head}}}
---------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'

This is the error when inspecting from browser:
> Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAGVUABEAAAAAxuQAAQABAAAAAAAAAAAAAAAAAAAAA…eLo4GBkcWhIzkkAqQkEggceHw5HFkM2VRZJFlYebR2MP5v3cDSu5GJwWUDW9xG1hQXAFAmKZU=' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by mpwashburn** [comment]
I figured out my very simplistic mistake. I was using a # when calling the section into the template.

**Comment by EthanRBrown** [comment]
Glad you figured it out!
