### ISSUE TITLE
CH05 mocha Cross-Page Test

### ISSUE THREAD

**Issue by oldmannt** [EthanRBrown/web-development-with-node-and-express#102]
Hi, Ethan

I am really enjoying your book.
But I stuck here:

after run 
$ mocha -u tdd -R spec qa/ tests-crosspage.js 2 >/ dev/ null
got this warning and nothing was tested:
Warning: Could not find any test files matching pattern: qa/test-crosspage.js
No test files found

**Comment by oldmannt** [comment]
nvm, path typo.

**Comment by EthanRBrown** [comment]
Glad you figured it out!  Also happy you're enjoying the book, thank you for the feedback, @oldmannt
