### ISSUE TITLE
incomplete credentials.js for mongodb

### ISSUE THREAD

**Issue by nyck33** [EthanRBrown/web-development-with-node-and-express#113]
![image](https://user-images.githubusercontent.com/25189545/89724988-0ab77e80-d9bf-11ea-9ba6-369468302aef.png)

That snippet at the top is incomplete with commas.  

Can you please include dummy `credential.js` with everything in it just for learning purposes?  It doesn't have to actually work but just so we can see the full structure and not be left with incomplete snippets.

**Comment by EthanRBrown** [comment]
Hi, @nyck33 yes, this is a frequently requested thing, so I'll go ahead and do that.  I had planned for something a little more elaborate...an interactive templated credentials generator, but I just have not been able to make time for that, and I've let "perfection be the enemy of good."  Will get something for you soon.
