### ISSUE TITLE
chapter 5 - getting 404 error in dev mode

### ISSUE THREAD

**Issue by csuarezgfx** [EthanRBrown/web-development-with-node-and-express#22]
I'm a noob who does not know how to diagnose this problem. I'm on page 44 and I have just added the pageTestScript. Upon running the site the qa js files produce a 404 error message when I inspect the page source. everythin loads but the tests-.js files. 

My code is typed identically to the book. I upgraded from express3-handlebars to express-handlebars and made sure package.json reflected these changes.  It looks like this.

in package.json:
```
"dependencies": {
    "express": "^4.12.3",
    "express-handlebars": "^2.0.0"
  },
```

in meadowlark.js:
```
var handlebars = require('express-handlebars').create({defaultLayout: 'main'});
...
app.use(function(req, response, next){
	response.locals.showTests = app.get('env') !== 'production' && 
	req.query.test === '1';
	next();// pass control to the next handler
})
...
app.get('/about', function(req,response){
	response.render('about', { 
		fortune: fortune.getFortune(),
		pageTestScript: '/qa/tests-about.js' 
	});
});
```

in main.handlebars:
```
{{#if showTests}}
		<div id= "mocha"></div>
		<script src="/vendor/mocha.js"></script>
		<script src="/vendor/chai.js"></script>
		<script>
			mocha.ui('tdd');
			var assert = chai.assert;
		</script>
		<script src="/qa/tests-global.js"></script>
		{{#if pageTestScript}}
			<script src="{{pageTestScript}}"></script>
		{{/if}}
		<script>mocha.run();</script>
	{{/if}}
```
I get this error:
![meadowlark errors](https://cloud.githubusercontent.com/assets/11609513/6818221/6ce2b088-d282-11e4-8f84-a528e1f71fbb.png)

I know this is probably a simple problem to fix but please bare with me I am teaching myself web development. Thanks

CS

**Comment by csuarezgfx** [comment]
UPDATE: I get the same errors using exoress3-handlebars.

**Comment by EthanRBrown** [comment]
Thank you!  Sorry I haven't been very responsive here...I'm playing catch-up with my various project.
