### ISSUE TITLE
Cannot read property 'Store' of undefined

### ISSUE THREAD

**Issue by johnwargo** [EthanRBrown/web-development-with-node-and-express#32]
I'm using the downloaded code to test the app as I work through the chapters and I'm running into a problem:

\node_book\meadowlark\site\node_modules\session-mongoose\index.js:261
    })(connect.session.Store);
                      ^
TypeError: Cannot read property 'Store' of undefined
    at module.exports (\node_book\meadowlark\site\node_modules\session-mongoose\index.js:261:23)
    at Object.<anonymous> (\node_book\meadowlark\site\meadowlark.js:88:52)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
12 Jul 08:46:33 - [nodemon] app crashed - waiting for file changes before starting...

Any ideas what's happening here? I made sure I had the latest versions of the node modules. Some posts suggest that I should add node-connect, but that didn't change anything. Any thoughts?

**Comment by johnwargo** [comment]
Nevermind, figured it out.

**Comment by EthanRBrown** [comment]
Thanks, John, I was just getting around to digging into your problem.  I'm glad you figured it out.

**Comment by ywgu** [comment]
What's the solution? I got the same issue.

**Comment by EthanRBrown** [comment]
Hi, @johnwargo , I too am curious about the solution...I imagine it's a `session-mongoose` version issue...undoubtedly they changed the name of something?  Curious minds would like to know....

**Comment by johnwargo** [comment]
Oh, gosh, I have no idea.  Sorry. I should have posted the solution.  I didn't, so it must have been something stupid on my end.  If I think of it, I'll come back and post

**Comment by underser** [comment]
The solution for me be:
 - remove latest version of connect(that be 3.5.0)
 - install connect version 2.0.0

**Comment by drizzyemtk54** [comment]
Use

const session = require('express-session');
const MongoStore = require('connect-mongo')(session);

instead of just
const session = require('express-session');
const MongoStore = require('connect-mongo');

it worked for me.been trying to solve that issue for the past hour.
