### ISSUE TITLE
Bundles?

### ISSUE THREAD

**Issue by johnwargo** [EthanRBrown/web-development-with-node-and-express#33]
In Chapter 16, you briefly mention your bundle module, and show how to use it, but you don't explain it.  I don't understand how the 'stuff' in the config.js file relates to stuff like this:

{{#each _bundles.css}}
    <link rel="stylesheet" href="{{static .}}">
{{/each}}

I understand, I think, what I'm doing when I bundle, but you aren't explaining what happens. How would I know, or where would I find that _bundles.css relates to bundles.clientJavaScript.contents (which is what I'm pretty sure is what's happening here)?

**Comment by EthanRBrown** [comment]
Thanks for the comment, John...I will put a note in my TODO list for the next book revision to revisit my explanation of this.  There is documentation on the package's npm page (https://www.npmjs.com/package/connect-bundle), but I will see if I can shore up the explanation in the book as well.
