### ISSUE TITLE
Ch 5. Missing dependencies in the test files with Grunt Setup?

### ISSUE THREAD

**Issue by philkeys** [EthanRBrown/web-development-with-node-and-express#34]
I made the shift over to the grunt setup at the end of chapter 5. However, when I ran 'grunt' a few errors occurred.

Two of the tests, 'public/qa/tests-about.js' and 'public/qa/tests-global' were erroring out saying that 'assert' was not defined. So, I added in chai's assert via require, and then ran 'grunt' again.

For the tests-about.js file, now it was showing that '$' was not defined. So I found the jQuery npm module and after installing used the require to bring that in. However, after that it said that undefined was not a function.

For the tests-global, it said 'document is not defined'. So  I did a little searching and thought possibly that I needed to bring in jsdom. I gave that a go but after running grunt it came back with 'Unspecified AssertionError'.

Any ideas? Thanks a lot!

**Comment by EthanRBrown** [comment]
I'll look into this Phil, thanks for the heads-up.

**Comment by EthanRBrown** [comment]
So something is fishy here....  `public/qa/tests-about.js` and `public/qa/tests-global.js` are for _browser_ testing only.  Star up the server, and add `?test=1` to the URL, and these tests will run.  They're not intended to run server-side via grunt.  The server-side tests are all in `qa` (not `public/qa`).  Out of the box, the gruntfile doesn't pull these tests in...did you add them, or...?

**Comment by EthanRBrown** [comment]
I verified the server-side tests (in `qa`) and the browser-side tests (by starting the server and adding `?test=1` to the URL) are working (Linux, latest on master).

**Comment by philkeys** [comment]
Gotcha. I still had all my tests within a qa folder inside public and hadn't moved the two out. Made the changes and it's all working. 

Thank you so much for the quick response!!
