### ISSUE TITLE
Callback function of connect-rest

### ISSUE THREAD

**Issue by pietrofxq** [EthanRBrown/web-development-with-node-and-express#36]
I'm a bit confused about the use of connect-rest.

The third passed parameter is the 'callback' function. What exactly this function does? It returns what you want as json? Why the first argument is "null"? The documentation doesn't seem to explain much about this

**Comment by EthanRBrown** [comment]
Hi, Pietro; could you post a code sample?  `connect-rest` has multiple use cases....

**Comment by pietrofxq** [comment]
Yeah, for example:

```javascript
rest.get('/attraction/:id', function(req, content, cb){
 Attraction.findById(req.params.id, function(err, a){
  if(err) return cb({ error: 'Unable to retrieve attraction.' });
  cb(null, {
   name: attraction.name,
   description: attraction.description,
   location: attraction.location,
  });
 });
});
```

What ```cb``` does in this case isn't clear for me.

**Comment by EthanRBrown** [comment]
`connect-rest` supports two calling conventions: synchronous and asynchronous.  What you're asking about is the asynchronous convention.  Let's start with the synchronous call to understand the difference:

```javascript
rest.get('/attraction/:id', function(req, content) {
  // note that we didn't provide a callback parameter:
  // no asynchronous behavior here!
  return {
      name: "test",
      description: "test",
      location: "test",
});
```

This is fine if you're not doing any asynchronous processing.  If you are (as in the case with `Attraction.find`), this won't work:

```javascript
rest.get('/attraction/:id', function(req, content) {
    // Attraction.findById doesn't simply return its result, so we can't return it here....
   Attraction.findById(req.params.id, function(err, a){
       // and we can't meaningfully return here, because we'd simply
       // be returning from the anonymous function, which does nothing....
    }
   // implicitly returns undefined...which is what the endpoint will return to the client
});
```

As you can see, when you're calling an async function, there's no way to make it work without a callback.  The callback that `connect-rest` passes in allows you to operate in an async context.  Essentially, when you use the callback parameter, `connect-rest` won't complete the request until you invoke that callback.  When you do invoke the callback, the first parameter is the error (use `null` for no error), and the second parameter is the payload you want sent with the request.

I hope this makes it clearer....

**Comment by pietrofxq** [comment]
Yeah, now I understand.

Thanks for the explanation Ethan. I appreciate your work and your support
:-)

2015-08-22 14:22 GMT-03:00 Ethan Brown <notifications@github.com>:

**Comment by EthanRBrown** [comment]
Great!  I'm glad I was able to help.
