### ISSUE TITLE
set custom layout fail

### ISSUE THREAD

**Issue by wewea** [EthanRBrown/web-development-with-node-and-express#43]
i have already create an custom.handlebars in views/layouts/. it didn't work. eventhough i set layoutDirs when create the engine. 

is there something wrong with my code?
```javascript
app.get('/custom-layout', function (req ,res) {
  res.render('custom-layout', {layout: 'custom'});
});
```
here is error info:
```
Error: Failed to lookup view "custom-layout" in views directory "/home/zhlin/Co
de/Express/chap3/site/views"
...
```

**Comment by EthanRBrown** [comment]
You said you set `layoutDirs`, but it should be `layoutsDir` (plural _layouts_, singular _dir_)...that would be the first thing I'd check....

**Comment by wewea** [comment]
yeah, there is a typo. thank you.

but i think the problem is that i put the custom.handlebars in views/layouts/ instead of views/. after i point out the path explictly, it work withiout set the layoutsDir.

```javascript
app.get('/custom-layout', function (req, res) {
  res.render('layouts/custom', {layout: 'custom'});
});
```
thanks for reply .

**Comment by EthanRBrown** [comment]
Hm...don't confuse the layout with the view!  In your updated example, you're rendering `layouts/custom` as a view, but that's also the template you're using...so you're using the same for both.  Probably not what you want....  Layouts should go in `views/layouts`, and views should go in `views` (or subdirectories thereof that are not `layout`).

**Comment by wewea** [comment]
Oh, I got it. I have to create an 'custom-layout.handlebars' in views/ at the same time.
so it compile in this turn:
> views/custom-layout.handlebars -> views/layouts/custom.handlebars

```javascript
app.get('/custom-layout', function (req, res) {
  res.render('custom-layout', {layout: 'custom'});
});
```
