### ISSUE TITLE
In this book it says npm is not an acronym

### ISSUE THREAD

**Issue by vasco3** [EthanRBrown/web-development-with-node-and-express#46]
doesn't **npm** stands for node package manager?

**Comment by EthanRBrown** [comment]
Common misconception.  https://docs.npmjs.com/misc/faq#if-npm-is-an-acronym-why-is-it-never-capitalized

**Comment by vasco3** [comment]
oh interesting. That was fast! thanks

**Comment by EthanRBrown** [comment]
No problem...and honestly, I think it's a little bit precious on part of the npm folks.  There's some tradition there (see PHP and Gnu), but it's kind of a silly tradition.  Programmers just trying to be ridiculous.

**Comment by vasco3** [comment]
I see, those silly things keep it fun :)
