### ISSUE TITLE
problem  length jquery 

### ISSUE THREAD

**Issue by pipecivil** [EthanRBrown/web-development-with-node-and-express#49]
assert($('a[href="/contact"]').length);
Hi! dear my friend

your book is great for me
but now have problem
I can't solve this problem
let me know how to fix it

<img width="724" alt="2015-12-18 12 21 27" src="https://cloud.githubusercontent.com/assets/4828753/11873374/81182f6a-a51d-11e5-99ab-e8c0eb8f67d1.png">
<img width="699" alt="2015-12-18 12 22 01" src="https://cloud.githubusercontent.com/assets/4828753/11873373/8116781e-a51d-11e5-844b-637fb4dfbc23.png">

**Comment by pipecivil** [comment]
I have known what am I wrong


 <a href="/contact">contact us</a>
		var j = $('a[href="/contact"]').length;
		alert(j);

if main.handlebars  execute this jquery
alert value is 1

but in the 
about.handlebars is 0

I am thinking about it



<img width="1128" alt="2015-12-18 8 37 06" src="https://cloud.githubusercontent.com/assets/4828753/11885174/b773059a-a562-11e5-90de-86b4c4784811.png">


the problem is on display print not html
like text/plain 
So, I think it's alert value is 0

but I don't know how am I solve this problem
would you please teach me

thank you

**Comment by pipecivil** [comment]
any way if I put this code
'''html
<a href="/contact">contact us</a>
'''
on main.handlebars
it is ok!

thank you have a nice day

**Comment by pipecivil** [comment]
wow, 
Finally I found it
{{{body}}}
I have to use triple-stash

**Comment by EthanRBrown** [comment]
Sorry I didn't get to this in time to save you some trouble!  Yes, the triple curly brackets are required to prevent HTML interpolation.  I'm glad you figured it out!

**Comment by pipecivil** [comment]
thank you so much 
I like your book

**Comment by EthanRBrown** [comment]
Thank you, I'm glad you've enjoyed it!
