### ISSUE TITLE
mocha no work

### ISSUE THREAD

**Issue by maomaoking** [EthanRBrown/web-development-with-node-and-express#51]
hello , i learn   ch05. but when i open two terminal . the first code 'node meadowlark.js'. the second code ' mocha -u tdd -R qa/tests-crosspage.js 2>/dev/null'  . it's nothing to show me in the first terminal. can you help me . thank you very much -----  orz

**Comment by maomaoking** [comment]
my product is https://github.com/maomaoking/meadownlark  . you can download and try . isn't work? >_<

**Comment by Jammerwoch** [comment]
Do you see anything in the first console?  You should see:

    Express started on http://localhost:3000; press Ctrl-C to terminate.

If that works, try connecting to http:/localhost:3000 in a browser; you should see some routes in the console window.

**Comment by maomaoking** [comment]
i can't believe that i can get your reply  ^_^ 
when i start node server i can see 
`Express started on http://localhost:3000; press Ctrl-C to terminate.` 
when i connect http:/localhost:3000 in a browser ; i can see 
`GET / 200 33.450 ms - 341
GET /img/logo.jpg 304 3.742 ms - -`
but when i exec 'mocha -u tdd -R spec qa/tests-crosspage.js 2>/dev/null' on the second console 
the first console nothing to show ??

**Comment by Jammerwoch** [comment]
Try leaving off the redirect of standard error...I suspect there's something wrong with the installation of Zombie:

    mocha -u tdd -R spec qa/tests-crosspage.js

(notice the omitted `>/dev/null`.)  Also, what OS are you on?

**Comment by maomaoking** [comment]
i think so . the wrong is zombie~~
when i exec 
`mocha -u tdd -R spec qa/tests-crosspage.js`
the console show error log :
_/Users/zhangyumou/3_source/8_frame/node/meadownlark/site/node_modules/zombie/node_modules/jsdom/lib/jsdom/living/node-iterator.js:3_
_const defineGetter = require("../utils").defineGetter;_
_^^^^^_
_SyntaxError: Use of const in strict mode._
......

and my os is OSX ^_^

**Comment by Jammerwoch** [comment]
Now I suspect your problem is that you're using an outdated version of Node.  Could you type `node -v` and let me know what version you're on?

It should not be complaining about `const` in strict mode.

**Comment by maomaoking** [comment]
v0.12.7

**Comment by EthanRBrown** [comment]
Hm...well that is very odd.  I just tried it with Node 0.12.7, and it worked fine...I didn't get that error.

Regardless, 0.12.7 is pretty old, why don't you update to the latest (4.2.4).  Then you'll want to delete your `node_modules` directory (`rm -rf node_modules`) and run `npm install` again.  Let me know if the problem persists after doing this....

**Comment by maomaoking** [comment]
sorry  . the yesterday is so busy . thanks for your idea. i update the version and rm the node_modules and npm install .then start node .then...........it's ok .
thankyou verymush help me solve the problem
at last . Happy every day in 2016

**Comment by EthanRBrown** [comment]
I'm glad that worked out!  Best of luck to you.
