### ISSUE TITLE
The completed sample is required to operate at Heroku server hosting 

### ISSUE THREAD

**Issue by thebigsmall** [EthanRBrown/web-development-with-node-and-express#57]
I would appreciate if you fill this function below .. 

Chapter 8 and Chapter 13: 
function saveContestEntry(contestName, email, year, month, photoPath){
 // TODO...this will come later
}

The completed sample is required to operate at Heroku server hosting
because of the following error 

Error: EXDEV: cross-device link not permitted, rename '/tmp/upload_f8c7f27f5fc96f1455e35cb30e2c7399' -> '/app/uploads/property/photo/1453171290731/사당휴브리지오피스텔검색결과.jpg'

And 
i would like to done my first sample works..
http://helloslow.herokuapp.com/

**Comment by EthanRBrown** [comment]
I'm afraid I can't complete every part of this application; this is not designed to be a complete working example with all functionality implemented.  You should have the knowledge you need to complete this: review the chapter on using MongoDB.  It would look something like this:

    function saveContestEntry(contestName, email, year, month, photoPath, cb) {
        Contest.findOne({ name: contestName }, function(err, contest) {
            if(err) return cb(new Error("Invalid contest: " + contestName));
            new ContestEntry({
                contest: contest,
                email: email,
                year: year,
                month: month,
                photoPath: photoPath
            }).save(cb);
        });
    }

Of course you'll also need to create models for `Contest` and `ContestEntry`, and you'll probably want some more sophisticated storage (like Amazon S3 or Azure) for the actual photos.  You should have everything you need to create this.  If you want to fully implement this, I might accept a PR with the completed code, although I think a full implementation is beyond the scope of the book.

Good luck!
