### ISSUE TITLE
Chapter 05 - First Mocha Test

### ISSUE THREAD

**Issue by mikevarela** [EthanRBrown/web-development-with-node-and-express#58]
I'm getting 2 failures. 1 for sure is the oregon page as it's not written but the other is dumbfounding me. I've checked spelling and can't figure it out. 
***\* (i've seen an earlier thread on zombie versions too so I've downgraded to version 3.1.1)

the error is

  Cross-Page Tests
    1) requesting a group rate quote from the hood river tour page should populate the referrer field
    2) requesting a group rate from the oregon coast tour page should populate the referrer field
    ✓ visiting the "request group rate" page directly should result in an empty referrer field

  1 passing (4s)
  2 failing

  1) Cross-Page Tests requesting a group rate quote from the hood river tour page should populate the referrer field:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

  2) Cross-Page Tests requesting a group rate from the oregon coast tour page should populate the referrer field:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

***\* note, just saw the missing {{section}} added to the request group rate page to allow jquery, I've added that and now all 3 of the test fail for the same reason, exceed timeout for done()

here's the error from terminal

Error: Missing helper: "section"
    at Object.<anonymous> (/Users/Mike/Training/Meadowlark/node_modules/handlebars/dist/cjs/handlebars/base.js:86:13)
    at Object.eval (eval at createFunctionContext (/Users/Mike/Training/Meadowlark/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:221:23), <anonymous>:6:91)
    at ret (/Users/Mike/Training/Meadowlark/node_modules/handlebars/dist/cjs/handlebars/runtime.js:159:30)
    at ret (/Users/Mike/Training/Meadowlark/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:488:21)
    at ExpressHandlebars._renderTemplate (/Users/Mike/Training/Meadowlark/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
    at ExpressHandlebars.<anonymous> (/Users/Mike/Training/Meadowlark/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

**Comment by SinOfWrath** [comment]
I had a similar issue(#50), you can check it, the problem was with version of Zombie being used.
Hope this helps.

**Comment by mikevarela** [comment]
Ok, thanks thats a big help.

I followed the suggestions anf the final one was correct.

Test had to change from 
assert(browser.field('referrer').value === 'referrer');
to
assert(browser.field('referrer').value === ' ');

and it works.

Also, Morgan, which was mentioned to help log is wonderful. Glad I installed it.

**Comment by EthanRBrown** [comment]
Sorry to be late to the parade on this one.  I'll be removing cross-browser testing with Zombie in the next edition of this book...there have just been too many problems with it, and I think there are better solutions now.

**Comment by markgreenwood** [comment]
Ethan, are you planning to go the Selenium route instead?

**Comment by SNPR** [comment]
Today I was in a similar situation (Error: Missing helper: "section").
Try to remove text 'jquery' from the code line {{#section 'jquery'}}.
It's helpful to me.

**Comment by EthanRBrown** [comment]
@markgreenwood I am actually planning on removing almost all technical discussion from this chapter.  Of all the chapters in the book, this is the one that has caused the most headaches and frustrations, both for me and my readers.  Testing tooling -- unlike a language or even a framework -- just changes too fast, and has too many platform quirks to be suitable for book content, a lesson I've learned the hard way.

I'm re-writing the test chapter to point to some other resources and discuss general testing principles, but I won't be demonstrating specific tools (certainly not Selenium, since that could be a whole book into itself).

**Comment by enchPench** [comment]
Hello guys.
The working solution is 

```
------------------------------

                var referrer = 'http://localhost:8080/tours/hood-river';

		browser.visit(referrer, function(){
			
			browser.clickLink('requestGroupRate', function(){
				
				assert(browser.resources[0].request.headers._headers[0][1] === referrer);
				done();
				
			});
		});
```
