### ISSUE TITLE
Ch 5 question about continuous integration for page tests

### ISSUE THREAD

**Issue by mknabe** [EthanRBrown/web-development-with-node-and-express#70]
Hi,
I just finished Ch 5, and I am trying to run the page tests in Travis CI. Can you point me in the right direction?

I can convert the tests to behave basically like the cross-page tests and that works, but I was wondering if there is a better way.

For anyone interested, I have the unit and cross-page tests working with these changes https://github.com/mknabe/MeadowlarkTravel/commit/69763f37b6b9a40a9cfd09557dd4b0247ef0a917
And page tests "working" with these changes https://github.com/mknabe/MeadowlarkTravel/commit/fdeb7eedfabcd64b4e69c85c0f85e22a08e947c4

Thanks for any help!

**Comment by norain2050** [comment]
1、the Zombile V3.1：may be good,but the lastest version is bad .

2、The Zombile master version have a bug,and also have been solved,but it havenot been merge to the master version .So,we are waiting....

Here is the bug:
https://github.com/estevanmaito/zombie/commit/5584faa980efe5809312983dcbd6697088793d55

**Comment by EthanRBrown** [comment]
I will be removing the cross-page tests with Zombie in the next edition of the book.  It's just been the cause of too much trouble and reader confusion, and I think there are better ways to fly now.
