### ISSUE TITLE
 JSHint:  'require' is not defined.'

### ISSUE THREAD

**Issue by vkelman** [EthanRBrown/web-development-with-node-and-express#74]
Not really an issue, just a question:

In chapter 5 you're saying, "If you’ve been following along, JSHint shouldn’t have any complaints about meadowlark.js".  However, it does complain saying that 'meadowlark.js: line 1, col 15, 'require' is not defined.'  etc.  It's a false positive,  right? But how to teach JSHint that require() is a built-in method of NodeJs?

**Comment by EthanRBrown** [comment]
JSHint has changed a lot since the book was written, and I haven't had an opportunity to go through and do a thorough update of the book, unfortunately.  I'm hoping to do that this summer.  I'll probably be moving from JSHint to ESLint at any rate!

**Comment by EthanRBrown** [comment]
@vkelman you're absolutely right about JSHint having changed a lot...and I too will be moving to ESLint in the next edition of the book
