### ISSUE TITLE
Zombie.js on Windows

### ISSUE THREAD

**Issue by vkelman** [EthanRBrown/web-development-with-node-and-express#77]
Just wanted to confirm: is it still impossible to install Zombie.js on Windows?
If possible, can someone provide links / instructions?
Is that hard for novice user like me?

**Comment by EthanRBrown** [comment]
Hi, @vkelman , it's not impossible (never has been), just very difficult.  I will be removing cross-page testing with Zombie in the next edition of this for this and many other reasons.

**Comment by romanson-god** [comment]
Now 2017, I installed latest zombie 5.0.7 via "npm install --save zombie".
It's working on Windows, I have Windows XP, yes it still live:)
As I understand, now Zombie has its own assertions, so we don't need Chai for it.
1. Remove "assert = require('chai').assert;", just leave requiring zombie.
2. Replace strings like this "assert(browser.field('referrer').value === referrer);"
with "browser.assert.element('form input[name=referrer]',referrer);"

**Comment by EthanRBrown** [comment]
Thanks for weighing in, @romanson-god ; glad to hear it's working on Windows.

**Comment by fullstack681** [comment]
@romanson-god, @EthanRBrown , ya may be it works on windows, but in some related zombieJS when i import in certain file, issue has shown below

Issue:
Uncaught ReferenceError: require is not defined

**Comment by fullstack681** [comment]
@romanson-god, @EthanRBrown , ya may be it works on windows, but i've some issue related to zombieJS when i import i.e.require in certain file, issue has shown below

Issue:
Uncaught ReferenceError: require is not defined
