### ISSUE TITLE
Chapter 7: Sections

### ISSUE THREAD

**Issue by kilgarenone** [EthanRBrown/web-development-with-node-and-express#81]
Hello, 

I'm stuck in the 'Sections' part of the templating with handlebars chapter. 

I have added the section helper to express3-handlebars instance, created the 'views/jquerytest.handlebars', and placed '{{{_sections.head}}}' and '{{{_sections.jquery}}}' in the layout.

But the corresponding 'sections' are missing in the DOM. Am I missing something?

**Comment by rockoff** [comment]
Have same problem. "express-handlebars": "^3.0.0"

**Comment by rockoff** [comment]
My тemporary solution for this issue:
...
if(!**app.locals**._sections) **app.locals**._sections = {};
**app.locals**._sections[name] = options.fn(this);
...

**Comment by ABordewyk** [comment]
Have you updated the section of your app's js file where the handlebars engine is set up? It should look something like this-

```
var handlebars = require('express-handlebars').create({
  defaultLayout:'main',
  helpers: {
    section: function(name, options){
      if(!this._sections) this._sections = {};
      this._sections[name] = options.fn(this);
      return null;
    }
  }
});
```

**Comment by kilgarenone** [comment]
@rockoff I tried your solution but didn't work :( . Do I have to change anything elsewhere? Thanks!

@metalsh33p Yeah, that's exactly what the book says, but doesn't work :(

**Comment by metalsh33p** [comment]
Is your learn-Express repository currently up-to-date? I'm looking at the app.js file and there isn't any routing for the jquery-test view. I was able to download your project and have the view work by adding the following route-
```
app.get('/jquery-test', function(req, res){
	res.render('jquery-test');
});
```

**Comment by reybango** [comment]
@metalsh33p yep that's the issue. Unfortunately it's not mentioned in the book. I just ran into this right now. @EthanRBrown, noting this so you can update for the 2ed. of the book.

**Comment by kilgarenone** [comment]
@metalsh33p I noticed in your code snippet was using 'express-handlebars' as opposed to 'express3-handlebars' as written in the book. So I installed the 'express-handlebar' and start using it. But now it can't render the 'home':

_Error: You must pass a string or Handlebars AST to Handlebars.compile. You passed [object Object]_

So I used back the 'express3-handlebar' package and added the route for 'jquery-test'. It works on /jquery-test page. But I'm still confused how does that achieve the purpose of 'sections' as stated in the book, which is to inject sections into different parts of my layout by using `{{{_sections.head}}}` and `{{{_sections.jquery}}}` ?

**Comment by reybango** [comment]
@kilgarenone re: the sections, what you're basically doing in your layout page (main.handlebars) is creating placeholders where your specialized code should sit. That specialized code is what you define in the sections on each template page. The premise behind it is that each page may have specific & unique functionality that needs to be included. So for about.handlebars, you may want to include jQuery code that's unique to that page or perhaps you want to include a specific meta tag in the header for that page. 

 It'll definitely become more evident in the subsequent chapters where you'll see how you'll leverage these placeholders in main.handlebars to include the unique code necessary to do Ajax calls and more.

**Comment by kilgarenone** [comment]
Many thanks to @reybango and @metalsh33p !! I just wrapped my head around it..

One last thing if I may and probably a different issue: Should I continue to stick with 'express3-handlebar' or switch to the 'express-handlebar' package?

**Comment by reybango** [comment]
@kilgarenone definitely switch to express-handlebar since it's the package that the maintainers have switched to and will give you the updates you'll need.

**Comment by EthanRBrown** [comment]
Thanks for the notes everyone, and this is definitely one of the things I'll be fixing in the next edition of the book.
