### ISSUE TITLE
ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by reybango** [EthanRBrown/web-development-with-node-and-express#88]
Hey all, in ch18 I'm asked to install `csurf` to help prevent CSRF.  Unfortunately I keep getting the following error message: 

> ForbiddenError: invalid csrf token

I've:

- compared the code to the ch18 repo
- installed the older version of the package
- used the code samples from the `csurf` page
- tried changing the position of the middleware definition
- deleted any errant cookies
- confirmed that the token is being added to the hidden form field
- confirmed in Chrome DevTools that the hidden field's value is being passed

And nothing seems to work. I'm stumped at this point.  

Any ideas?

Code line for reference: [https://github.com/reybango/meadowlark/blob/master/meadowlark.js#L129](https://github.com/reybango/meadowlark/blob/master/meadowlark.js#L129)

**Comment by reybango** [comment]
Figured it out. The call to `csurf` needs to be below the call to `body-parser`. Found it via the `csurf` Github issue tracker. https://github.com/expressjs/csurf/issues/52#issuecomment-73981858

**Comment by AliAtrash** [comment]
Thanks! Had the same problem.
