### ISSUE TITLE
Chapter 13: MongoError: failed to connect to server [localhost:27017] on first connect

### ISSUE THREAD

**Issue by simplist88** [EthanRBrown/web-development-with-node-and-express#92]
Hi Ethan,

I'm learning node.js with your awesome book. unfortunately I stuck in chapter 13, regarding mongo DB connection. 

I'm getting "MongoError: failed to connect to server [localhost:27017] on first connect" every time I attempt to run server on my local machine. 

I've connected to hosted DB with URL provided by mlab console. do you have any clue what is causing this issue?

**Comment by EthanRBrown** [comment]
Can you share the connection string you're using?  You can redact the username/password information (just show it as `user:****` or whatever).

**Comment by simplist88** [comment]
Hi Ethan,

Fortunately it was just typo mistake.. guess I should be more patient before raising issue here..!

**Comment by EthanRBrown** [comment]
No problem, glad you were able to solve it!
