### ISSUE TITLE
ch10 body-parser error

### ISSUE THREAD

**Issue by duckhee** [EthanRBrown/web-development-with-node-and-express#93]
hi I have a problem I try ch 10 another error. It is parse error.
Error: Parse error on line 67:
...pt>
--------------------^
Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'
at Object.parseError (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
at Object.parse (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
at HandlebarsEnvironment.parse (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
at compileInput (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:514:19)
at ret (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
at ExpressHandlebars._renderTemplate (/home/won/Desktop/work/workspace/nodejs/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
at ExpressHandlebars. (/home/won/Desktop/work/workspace/nodejs/node_modules/express-handlebars/lib/express-handlebars.js:173:21)
Error: Parse error on line 67:
...pt>
--------------------^
Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF'
at Object.parseError (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
at Object.parse (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
at HandlebarsEnvironment.parse (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:43)
at compileInput (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:514:19)
at ret (/home/won/Desktop/work/workspace/nodejs/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:523:18)
at ExpressHandlebars._renderTemplate (/home/won/Desktop/work/workspace/nodejs/node_modules/express-handlebars/lib/express-handlebars.js:247:12)
at ExpressHandlebars. (/home/won/Desktop/work/workspace/nodejs/node_modules/express-handlebars/lib/express-handlebars.js:173:21)

this error code how to fix it .... I try exam but, exam is making server error.
I don't know could you help me, plz??
this is source meadowlark.js

var fortune = require('./lib/fortune.js') ;

var express = require('express') ;

var formidable = require('formidable') ;

var jqupload = require('jquery-file-upload-middleware') ;

var credentials = require('./credentials.js') ;

var app = express() ;

var handlebars = require('express-handlebars').create({defaultLayout: 'main', helpers: {section: function (name, options) {
if(!this._sections){
this._sections = {} ;
}
this._sections[name] = options.fn(this) ;
return null ;
}
}
}) ;

app.engine('handlebars', handlebars.engine) ;
app.set('view engine', 'handlebars') ;

app.set('port', process.env.PORT || 3000) ;

app.disable('X-powered-by') ;

app.use(require('cookie-parser')(credentials.cookieSecret)) ;

app.use(require('express-session')({
resave: false,
saveUninitialized: false,
secret: credentials.cookieSecret,
})) ;

app.use(express.static(__dirname + '/public')) ;

app.use(require('body-parser')()) ;

app.use(function(req, res, next) {
res.locals.flash = req.session.flash ;
delete req.session.flash ;
res.locals.showTests = app.get('env') !== 'production' && req.query.test === '1' ;
next() ;
}) ;

function getWeatherData() {
return {
locations: [
{
name: 'Portland',
forecastUrl: 'http://www.wunderground.com/US/OR/Portland.html',
iconUrl: 'http://icons-ak.wxug.com/i/c/k/cloudy.git',
weather: 'Overcast',
temp: '54.1 F (12.3 C)',
},
{
name: 'Bend',
forecastUrl: 'http://www.wunderground.com/US/OR/Bend.html',
iconUrl: 'http://icons-ak.wxug.com/i/c/k/partlycloudy.git',
weather: 'Partly Cloudy',
temp: '55.0 F (12.8 C)',
},
{
name: 'Manzanita',
forecastUrl: 'http://www.wunderground.com/US/OR/Manzanita.html',
iconUrl: 'http://icons-ak.wxug.com/i/c/k/rain.git',
weather: 'Light Rain',
temp: '55.0 F (12.8 C)',
},
],
} ;
}

app.use(function(req, res, next) {
if(!res.locals.partials){
res.locals.partials = {} ;
}
res.locals.partials.weatherContext = getWeatherData() ;
next() ;
}) ;

app.use('/update', function(req, res, next) {
var now = Date.now() ;
jqupload.fileHandler({
uploadDir: function() {
return __dirname + '/public/uploads/' + now ;
},
uploadUrl: function() {
return '/uploads/'+now ;
},
})(req, res, next) ;
}) ;

app.use(require('cookie-parser')(credentials.cookieSecrept)) ;

app.get('/headers', function(req, res) {
res.set('Content-Type', 'text/plain') ;
var s = '' ;
for(var name in req.headers) {
s += name + ':' + req.headers[name] + '\n' ;
}
res.send(s) ;
}) ;

app.get('/', function(req, res) {
res.render('home') ;
});

app.get('/about', function(req, res) {
res.render('about', {fortune: fortune.getFortune(), pageTestScript: '/qa/tests-about.js' } ) ;
});

app.get('/tours/hood-river', function(req, res) {
res.render('tours/hood-river') ;
}) ;

app.get('/tours/oregon-coast', function(req, res) {
res.render('tours/oregon-coast') ;
}) ;

app.get('/tours/request-group-rate', function(req, res) {
res.render('tours/request-group-rate') ;
}) ;

app.get('/jquery-test', function(req, res) {
res.render('jquery-test') ;
}) ;

app.get('/nursery-rhyme', function(req, res) {
res.render('nursery-rhyme') ;
}) ;

app.get('/data/nursery-rhyme', function(req, res) {
res.json({
animal: 'squirrel',
bodyPart: 'tail',
adjective: 'bushy',
noun: 'heck',
}) ;
}) ;

app.get('/thank-you', function(req, res) {
res.render('thank-you') ;
}) ;

app.get('/newsletter', function(req, res) {
res.render('newsletter', {csrf: 'CSRF token goes here' }) ;
}) ;

function NewsletterSignup() {}
NewsletterSignup.prototype.save = function(cb) {
cb() ;
} ;

var VALID_EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;

app.post('/newsletter', function(req, res) {
	var name = req.body.name || '', email = req.body.email || '' ;
	if(!email.match(VALID_EMAIL_REGEX)) {
		if(req.xhr) {
			return res.json({ error: 'Invalid name email address.' }) ;
		}
		req.session.flash = {
			type: 'danger',
			intro: 'Validation error!',
			message: 'The email address you entered was not valid.',
		} ;
		return res.redirect(303, '/newletter/archive') ;
	}
	new NewletterSignup({name: name, email: email }).save(function(err) {
		if(err) {
			if(req.xhr) {
				return res.json({error: 'Database error.'}) ;
			}
			req.session.flash = {
				type: 'danger', 	
				intro: 'Database error!',
				message: 'There was a database error; please try again later.',
			} ;
			return res.redirect(303, '/newletter/archive') ;
		}
		if(req.xhr) {
			return res.json({ success: true }) ;
		}
		req.session.flash = {
			type: 'success',
			intro: 'Thank you!',
			message: 'You have now been signed up for the newsletter.',
		} ;
		return res.redirect(303, '/newletter/archive') ;
	}) ;
}) ;
app.get('/newsletter/archive', function(req, res) {
res.render('newsletter/archive') ;
}) ;

app.post('/process', function(req, res) {
if(req.xhr || req.accepts('json,html') ==='json') {
res.send({success: true }) ;
}else{
res.redirect(303, '/thank-you') ;
}
}) ;

app.get('/contest/vacation-photo', function(req, res) {
var now = new Date() ;
res.render('contest/vacation-photo', {year:now.getFullYear(), month: now.getMonth()
}) ;
}) ;

app.post('/contest/vacation-photo/:year/:month', function(req, res) {
var form = new formidable.IncomingForm() ;
form.parse(req, function(err, fields, files) {
if(err) {
return res.redirect(303, '/error') ;
}
console.log('received fields:') ;
console.log(fields) ;
console.log('received files:') ;
console.log(files) ;
res.redirect(303, '/thank-you') ;
}) ;
}) ;

app.get('/greeting', function(req, res) {
res.render('about', { message: 'welcome', style:req.query.style, userid: req.cookie.userid, username: req.session.username,}) ;
}) ;

app.get('/no-layout', function(req, res) {
res.render('no-layout', { layout: null }) ;
}) ;

app.get('/test', function(req, res) {
res.type('text/plain') ;
res.send('this is a test') ;
}) ;

app.post('/process-contact', function(req, res) {
console.log('Received contact from ' + req.body.name + ' <'+req.body.email + '>') ;
try{
return res.xhr ? res.render({success: true }) : res.redirect(303, '/thank-you') ;
}catch(ex) {
return res.xhr ? res.json({error: 'Database error.' }) : res.redirect(303, '/database-error') ;
}
}) ;

app.use(function(req, res, next) {
res.status(404) ;
res.render('404') ;
}) ;

app.use(function(err, req, res, next) {
console.log(err.stack) ;
res.status(500) ;
res.render('500') ;
}) ;

app.listen(app.get('port'), function() {
console.log('Expresss started on http://localhost:' + app.get('port')+'; press Ctrl + c to terminate') ;
}) ;

**Comment by EthanRBrown** [comment]
Hi, Won.  A little Googling tells me that the error you're getting points to an error in your Handlebars, not the JavaScript.  Can you provide the Handlebars code for the page that's producing this error?

Also, it's extremely hard to read these comments when you don't use Markdown formatting.  Instead of just dumping your code into a comment, please try to use the Markdown features, so your code is nicely formatted like this:

```js
app.use(function(err, req, res, next) {
  console.log(err.stack) ;
  res.status(500) ;
  res.render('500') ;
}) ;
```

It makes it much easier to diagnose the problem.

**Comment by duckhee** [comment]
do you mean not javaScript error? how to fix it?  I am not sure what it is mean ?? I don't have good english skill ... so don't understanding this means.... I try study back chater, and give me some advice study what chater?

**Comment by duckhee** [comment]
sorry for long answer and see you bad codding error stack

**Comment by EthanRBrown** [comment]
Hi, Won,

There's no need to apologize for your English; I don't speak any other languages, so It's always impressive to me when someone is bi-lingual!

I mean that I don't think your problem is in JavaScript, I think it's in one of your Handlebars (`.handlebars`) files.  Can you share the Handlebars file from the page you're trying to access when you get that error?

For example, if you're going to `/foo`, and you have the handler:

```js
app.get('/foo', function(req, res) {
  res.render('foo')
})
```

I want to see the file `views/foo.handlebars`.

**Comment by duckhee** [comment]
i got it this is may be hadlebars error ??  ok , i try fix main.handlebars, and study handlebars

**Comment by duckhee** [comment]
hi , this is main.handlebars code ... I try study, but couldn't find error code..
this is code

<!DOCTYPE html>
<html>
<head>
<meta charset = "utf-8">
<meta http-eequiv = "X-UA-Compatible" content = "IE=edge, chrome=1">
        <title>Meadowlark Travel</title>
        {{#if showTests}}
                <link rel = "stylesheet" href = "/vendor/mocha.css">
        {{/if}}
        {{{_sections.head}}}
        <meta name = "description" content = "">
        <meta name = "viewport" content = "width = device-width, initial-scale = 1">
        <script src = "//code.jquery.com/jquery-2.0.2.min.js"></script>
        <link rel = "stylesheet" href = "/vendor/bootstrap/css/bootstrap.min.css">
        <style>
                body{
                        padding-top:50px;
                        padding-bottom: 20px;
                }
        </style>
        <link rel = "stylesheet" href = "/vendor/bootstrap/css/bootstrap-theme.min.css">
        <link rel = "stylesheet" href = "/css/main.css">
        <script src = "/vendor/js/modernizr-2.6.2-respond-1.1.0.min.js"></script>
</head>
<body>
        <p class = "browsehappy">You are using an <strong>outdated</strong> browser. Please <a href = "http://browsehappy.com/">upgrade your browser</a> to improve your experience</p>
        <header><img src = "/img/apple.jpg" alt = "apple logo"></header>
        <div class = "container">
                {{#if flash}}
                        <div class = "alert alert-dismissible alert-{{flash.type}}">
                                <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">&times;</button>
                                <strong>{{flash.intro}}</strong> {{{flash.message}}}
                        </div>
                {{if}}

                {{{body}}}

                <hr>
                <footer>
                        <p>&copy;Meadowlark Travel </p>
                </footer>
        </div>
        <script>

**Comment by duckhee** [comment]
and this is home.handlebars code 

<h1>Welcome to Meadolark Travel</h1>
{{>weather}}

**Comment by EthanRBrown** [comment]
Hi, Won,

The problem is right here:

```
{{#if flash}}
<div class="alert alert-dismissible alert-{{flash.type}}">
<button type="button" class="close"
  data-dismiss="alert" aria-hidden="true">&times;</button>
<strong>{{flash.intro}}</strong> {{{flash.message}}}
</div>
{{if}}
```

The closing `{{if}}` is missing a slash.  It should be `{{/if}}`

**Comment by duckhee** [comment]
oh i see sorry for asking very simple error code .....  thanks you !!

**Comment by EthanRBrown** [comment]
No problem, Won, that happens to all of us!
